/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kma.cs.view;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import com.kma.cs.model.DatabaseCRUD;
import com.kma.cs.model.User;
import com.kma.cs.utils.HashUtil;
import java.awt.Font;

/**
 *
 * @author ptkat
 */
public class DangNhap extends javax.swing.JFrame {

	/**
	 * Creates new form DangNhap
	 */

	public static String userName;
	private static String password;
	public static String userId;
	public String userName2;

	public DangNhap() {
		initComponents();
		this.setLocation(400, 150);
		Font font = new Font("SansSerif", Font.PLAIN, 25);
        jButton_Login.setFont(font);
        jButton_Register.setFont(font);
        jLabel_Password.setFont(font);
        jLabel_UserName.setFont(font);
        jPasswordField_Password.setFont(font);
        jTextField_CryptoService.setFont(font);
        jTextField_UserName.setFont(font);
        Font font2 = new Font("SansSerif", Font.PLAIN, 60);
        jTextField_CryptoService.setText("Crypto Service");
        jTextField_CryptoService.setFont(font2);
        this.setTitle("Login");
//		this.setSize(1000, 500);
	}

	public void setUsername2(String userName2) {
		this.userName2 = userName2;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField_UserName = new javax.swing.JTextField();
		jLabel_Password = new javax.swing.JLabel();
		jLabel_UserName = new javax.swing.JLabel();
		jPasswordField_Password = new javax.swing.JPasswordField();
		jTextField_CryptoService = new javax.swing.JTextField();
		jButton_Login = new javax.swing.JButton();
		jButton_Register = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField_UserName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_UserNameActionPerformed(evt);
			}
		});

		jLabel_Password.setText("Password");

		jLabel_UserName.setText("UserName");

		jTextField_CryptoService.setText("Crypto Service");

		jButton_Login.setText("Login");
		jButton_Login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_LoginActionPerformed(evt);
			}
		});

		jButton_Register.setText("Register");
		jButton_Register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_RegisterActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(91, 91, 91)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jLabel_Password, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
				.addGap(58, 58, 58)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField_CryptoService, javax.swing.GroupLayout.PREFERRED_SIZE,
												470, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE,
														160, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(72, 72, 72).addComponent(jButton_Register,
														javax.swing.GroupLayout.PREFERRED_SIZE, 160,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 556,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE,
												556, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 237, Short.MAX_VALUE)))));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
								.addComponent(jTextField_CryptoService, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(64, 64, 64)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel_UserName, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(49, 49, 49)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE,
												55, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(68, 68, 68)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(121, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_UserNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_UserNameActionPerformed

	private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {
		userName = jTextField_UserName.getText().toString().trim();
		password = new String(jPasswordField_Password.getPassword()).toString().trim();
		password = HashUtil.hash(password);
		boolean check = false;
		try {
			String sqlSelect = "SELECT * FROM user";
			List list = DatabaseCRUD.getTable(sqlSelect, "user");
			List<Integer> listUserId = new ArrayList<Integer>();
			if (list != null) {
				if (list.size() >= 0) {
					check = false;
					for (Object object : list) {
						User user = (User) object;
//						password = HashUtil.hash(password);
//						System.out.println("user.getPassword():"+user.getPassword());
//						System.out.println("user.getUserName():"+user.getUserName());
//						System.out.println("password:"+password);
//						System.out.println("userName:"+userName);System.exit(0);
						if (user.getPassword().equals(password) && user.getUserName().equals(userName)) {
							userId = user.getUserId();
							JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
							userName2 = user.getUserName();
							check = true;
							CipherService service = new CipherService();
							service.setVisible(true);
							service.setUsername2(userName2);

							this.setVisible(false);
						}
					}
					if (!check) {
						JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin user");
					}

				}
			} else {
				JOptionPane.showMessageDialog(this, "Lỗi khi kết nốt tới cơ sở dữ liệu");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Lỗi không xác định");
		}

	}

	private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {
		DangKy dangKy = new DangKy();
		dangKy.setVisible(true);
		this.setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DangNhap().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_Login;
	private javax.swing.JButton jButton_Register;
	private javax.swing.JLabel jLabel_Password;
	private javax.swing.JLabel jLabel_UserName;
	private javax.swing.JPasswordField jPasswordField_Password;
	private javax.swing.JTextField jTextField_CryptoService;
	private javax.swing.JTextField jTextField_UserName;
	// End of variables declaration//GEN-END:variables
}
